### ISSUE TITLE
Is This Project Defunct?

### ISSUE THREAD

**Issue by threejeez** [fnproject/lb#14]
I have gone through the fn code and found load balancing login in there. Should we be using that or is that stuff being pulled out into this repo?

**Comment by rdallman** [comment]
yes, this repo is slated to be shot. we do need to make the lb stuff in fn core more easily executable - there is no main.go file to run out of the box. sorry that you invested time into figuring this out.

**Comment by threejeez** [comment]
Don’t worry about the time invested... I used it as an opportunity to dive into the code and learn, so it’s a net positive. We’re also chatting in slack so I’ll close this in favor of that. 

Thanks for the speedy reply!

**Comment by jgielstra** [comment]
Should the README.md mention this repo is deprecated and the functionality has been moved to the main fn binary ?

**Comment by rdallman** [comment]
we need to delete it, i'll ring the cow bell again
